DB-Application directory/project/admin/views.py
import datetime
from project import db, app
from project.models import Users, Employee, Department
from flask_login import login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from flask import render_template, request, Blueprint, redirect, url_for, session


########################################################################################################################
import logging
logging.basicConfig(format='[%(asctime)s] %(levelname)s in %(module)s: %(message)s',
                        filename=app.config['LOG_PATH'],
                        datefmt='%d-%b-%y %H:%M:%S',
                        level=logging.DEBUG,
                        filemode='a')
########################################################################################################################


admin_blueprint = Blueprint('admin', __name__, template_folder='templates')



@admin_blueprint.route('/admin-view', methods=['GET', 'POST'])
def login():
    session.clear()
    if request.method == 'POST':
        admin_email = request.form.get('admin_email', None)
        admin_password = request.form.get('admin_password', None)

        if admin_email == None:
            return render_template('admin.html', warning='Email cannot be empty')

        if admin_password == None:
            return render_template('admin.html', warning='Password cannot be empty')

        admin_obj = Employee.query.filter_by(email=admin_email).first()

        if admin_obj == None:
            logging.debug('{admin} does not exist'.format(admin=admin_email))
            return render_template('admin.html', warning='Email address does not exist!!!')

        admin_users_obj = Users.query.filter_by(emplid=admin_obj.emplid).first()
        if admin_obj is not None and check_password_hash(admin_users_obj.psw, admin_password):
            login_user(admin_obj)
            logging.debug('{admin} Logged In'.format(admin=admin_email))
            return redirect(url_for('admin.create_rc_hr_accounts'))
    return render_template ('admin.html')


@admin_blueprint.route('/create-rc-hr-accounts', methods=['GET', 'POST'])
@login_required
def create_rc_hr_accounts():
    dept_names = Department.query.all()
    department_list = [x.name for x in dept_names]

    if request.method == 'POST':
        email = request.form.get('email', None)
        name = request.form.get('username', None)
        password = request.form.get('password', None)
        type = request.form.get('gridRadios', None)
        department = request.form.get('department', None)
        repeat_password = request.form.get('repeat_password', None)

        dept_obj = Department.query.filter_by(name=department).first()

        if name == None:
            return render_template('hr_recruiter_account_create.html', warning='Username cannot be None')

        if email == None:
            return render_template('hr_recruiter_account_create.html', warning='Email cannot be None')

        if type == None:
            return render_template('hr_recruiter_account_create.html', warning='Type cannot be None')

        if password == None:
            return render_template('hr_recruiter_account_create.html', warning='Password cannot be None')

        if repeat_password == None:
            return render_template('hr_recruiter_account_create.html', warning='Repeat Password cannot be None')

        if password != repeat_password:
            return render_template('hr_recruiter_account_create.html', warning='Both passwords should be same')

        new_emp_obj = Employee(name=name,
                               email=email,
                               salary=10000,
                               status='Active',
                               deptid=dept_obj.deptid,
                               hire_dt=datetime.date.today())
        db.session.add(new_emp_obj)
        db.session.commit()
        logging.debug('New employee {name} created'.format(name=name))

        emp_obj = Employee.query.filter_by(email=email).first()
        emp_user_obj = Users(emplid=emp_obj.emplid,
                             deptid=dept_obj.deptid,
                             type=type,
                             psw=generate_password_hash(password))
        db.session.add(emp_user_obj)
        db.session.commit()
        return redirect(url_for('admin.create_rc_hr_accounts'))
    return render_template('hr_recruiter_account_create.html',department_list=department_list)


@admin_blueprint.route('/admin-logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('users.login'))

DB-Application directory/project/core/views.py
from flask import render_template, Blueprint


core_blueprint = Blueprint('core', __name__, template_folder='templates')

@core_blueprint.route('/')
def index():
    return render_template('index.html')

DB-Application directory/project/staff/views.py
import json
import datetime
import threading
from project import db, app
from werkzeug.security import check_password_hash
from flask_login import login_required, login_user, logout_user, current_user
from flask import render_template, request, Blueprint, redirect, url_for, session
from project.models import Users, Employee, Job, Department, Application, Applicant, Resume
from project.staff.emails import email_sending_logic, email_sending_logic_interview, email_sending_logic_offer


########################################################################################################################
import logging
logging.basicConfig(format='[%(asctime)s] %(levelname)s in %(module)s: %(message)s',
                        filename=app.config['LOG_PATH'],
                        datefmt='%d-%b-%y %H:%M:%S',
                        level=logging.DEBUG,
                        filemode='a')
########################################################################################################################

staff_blueprint = Blueprint('staff', __name__, template_folder='templates')


@staff_blueprint.route('/staff-login', methods=['GET', 'POST'])
def login():
    session.clear()
    if request.method == 'POST':
        staff_email = request.form.get('staff_email', None)
        staff_password = request.form.get('staff_password', None)

        if staff_email == None:
            return render_template('staff_login.html', warning='Email cannot be empty')

        if staff_password == None:
            return render_template('staff_login.html', warning='Password cannot be empty')

        staff_obj = Employee.query.filter_by(email=staff_email).first()
        if staff_obj == None:
            return render_template('staff_login.html', warning='Email address does not exist!!!. Please contact Admin.')

        staff_users_obj = Users.query.filter_by(emplid=staff_obj.emplid).first()
        if staff_obj is not None and check_password_hash(staff_users_obj.psw, staff_password):
            logging.debug('{name} User Logged In'.format(name=staff_obj.name))
            login_user(staff_obj)
            return redirect(url_for('staff.staff_jobs_view_create'))
    return render_template('staff_login.html')


@staff_blueprint.route('/staff-jobs-view-create', methods=['GET', 'POST'])
@login_required
def staff_jobs_view_create():

    current_emp_obj = Employee.query.filter_by(email=current_user.__dict__['email']).first()
    current_user_obj = Users.query.filter_by(emplid=current_emp_obj.emplid).first()
    isRecruiter = current_user_obj.type

    dept_names = Department.query.all()
    department_list = [x.name for x in dept_names]

    if isRecruiter == 'Recruiter':
        final_display_list = []
        all_application_obj = Application.query.all()

        if all_application_obj != []:
            for application in all_application_obj:
                application = application.__dict__
                job_id = application['jobid']
                applicant_id = application['app_id']
                job_obj = Job.query.filter_by(jobid=job_id).first()
                user_obj = Applicant.query.filter_by(app_id=applicant_id).first()
                resume_obj = Resume.query.filter_by(app_id=applicant_id).first()
                temp_dict = {}
                temp_dict["job_id"] = job_id
                temp_dict["job_title"] = job_obj.title
                temp_dict["user_name"] = user_obj.name
                temp_dict["applicant_id"] = applicant_id
                temp_dict["user_resume"] = resume_obj.resume
                temp_dict["status"] = application["status"]
                temp_dict["applied_date"] = datetime.datetime.strftime(application["appl_dt"], '%d %b %Y')
                final_display_list.append(temp_dict)


    elif isRecruiter == 'Hiring Manager':
        final_display_list = []

        all_application_obj = Application.query.all()
        list_of_jobs = Job.query.filter_by(deptid=current_emp_obj.__dict__['deptid']).all()

        if all_application_obj != []:
            for application in all_application_obj:
                application = application.__dict__
                job_id = application['jobid']
                applicant_id = application['app_id']

                for jobs in list_of_jobs:
                    if jobs.jobid == job_id:
                        user_obj = Applicant.query.filter_by(app_id=applicant_id).first()
                        resume_obj = Resume.query.filter_by(app_id=applicant_id).first()
                        temp_dict = {}
                        temp_dict["job_id"] = job_id
                        temp_dict["job_title"] = jobs.title
                        temp_dict["user_name"] = user_obj.name
                        temp_dict["applicant_id"] = applicant_id
                        temp_dict["user_resume"] = resume_obj.resume
                        temp_dict["status"] = application["status"]
                        temp_dict["applied_date"] = datetime.datetime.strftime(application["appl_dt"], '%d %b %Y')
                        final_display_list.append(temp_dict)


    if request.method == 'POST':
        form = request.form.get('action', None)
        if form == 'create_job':
            status = request.form.get('status', None)
            desc = request.form.get('job_desc', None)
            title = request.form.get('job_title', None)
            location = request.form.get('location', None)
            min_sal = request.form.get('min_salary', None)
            max_sal = request.form.get('max_salary', None)
            visibility = request.form.get('gridRadios', None)
            department = request.form.get('department', None)

            if visibility == 'visible':
                visibility = '1'
            else:
                visibility = '0'

            dept_obj = Department.query.filter_by(name=department).first()

            if title == None or title == '':
                return render_template('staff_jobs_view_create.html', warning='Job Title cannot be empty')
            if desc == None or desc == '':
                return render_template('staff_jobs_view_create.html', warning='Job Description cannot be empty')
            if visibility == None or visibility == '':
                return render_template('staff_jobs_view_create.html', warning='Job Visibility cannot be empty')
            if location == None or location == '':
                return render_template('staff_jobs_view_create.html', warning='Job Location cannot be empty')

            new_job_obj = Job(title=title,
                              status=status,
                              descr=desc,
                              location=location,
                              salary_min=min_sal,
                              salary_max=max_sal,
                              deptid=dept_obj.deptid,
                              visibility=visibility,
                              open_dt=datetime.date.today())
            db.session.add(new_job_obj)
            db.session.commit()
            logging.debug('New Job {title} Created'.format(title=title))
            return redirect(url_for('staff.staff_jobs_view_create'))
        else:
            if request.method == 'POST':
                res = request.form.to_dict()
                res = res["action"].replace("'", '"')
                ap = res[1:-8]
                action = res[-6:-1]
                res = json.loads(ap)

                if action == '"rev"':
                    app_name = Applicant.query.filter_by(app_id=res['applicant_id']).first().name
                    job_name = Job.query.filter_by(jobid=res['job_id']).first().title
                    logging.debug('{aname} Reviewed for Job {jname}'.format(aname=app_name, jname=job_name))
                    department_list, final_display_list = commonSaveLogic("Reviewed", res)

                if action == '"rej"':
                    app_name = Applicant.query.filter_by(app_id=res['applicant_id']).first().name
                    job_name = Job.query.filter_by(jobid=res['job_id']).first().title
                    logging.debug('{aname} Rejected for Job {jname}'.format(aname=app_name, jname=job_name))
                    department_list, final_display_list = commonSaveLogic("Rejected", res)

                if action == '"int"':
                    app_name = Applicant.query.filter_by(app_id=res['applicant_id']).first().name
                    job_name = Job.query.filter_by(jobid=res['job_id']).first().title
                    logging.debug('{aname} Interviewed for Job {jname}'.format(aname=app_name, jname=job_name))
                    department_list, final_display_list = commonSaveLogic("Interviewed", res)
                    email_thread = threading.Thread(target=email_sending_logic_interview, args=(res['job_id'], res['applicant_id']))
                    email_thread.start()

                if action == '"off"':
                    app_name = Applicant.query.filter_by(app_id=res['applicant_id']).first().name
                    job_name = Job.query.filter_by(jobid=res['job_id']).first().title
                    logging.debug('{aname} Offered for Job {jname}'.format(aname=app_name, jname=job_name))
                    department_list, final_display_list = commonSaveLogic("Offer", res)
                    email_thread = threading.Thread(target=email_sending_logic_offer, args=(res['job_id'], res['applicant_id']))
                    email_thread.start()

                if action == '"hir"':
                    app_name = Applicant.query.filter_by(app_id=res['applicant_id']).first().name
                    job_name = Job.query.filter_by(jobid=res['job_id']).first().title
                    logging.debug('{aname} Hired for Job {jname}'.format(aname=app_name, jname=job_name))
                    rejectOtherCandidates(res['job_id'], res['applicant_id'])
                    department_list, final_display_list = commonSaveLogic("Hired", res)

DB-Application directory/project/templates/admin.html
{% extends "base.html" %}
{% block content %}

{% if warning %}
<div class="alert alert-warning" role="alert">
  {{warning}}
</div>
{% endif %}

{% if success %}
<div class="alert alert-success" role="alert">
  {{success}}
</div>
{% endif %}

<div class="jumbotron">
    <h2 align="center">PLEASE LOGIN FOR 
        ADMIN ACCESS
        </h2><br><br>
  <form method="POST">

    <div class="form-group">
      <label for="exampleInputEmail1">Admin email address</label>
      <input type="email" class="form-control" name="admin_email" aria-describedby="emailHelp" placeholder="Enter your email">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">Admin password</label>
      <input type="password" class="form-control" name="admin_password" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

DB-Application directory/project/templates/applicant-view.html
{% extends "base.html" %}
{% block content %}

{% if warning %}
<div class="alert alert-warning" role="alert" align="center">
  {{warning}}
</div>
{% endif %}

{% if user_name %}
<h1>Welcome {{ user_name }}!!!</h1>
{% endif %}

<div class="jumbotron">
  {% if total_job_count == 0 %}
  <h2>NO JOBS POSTED YET</h2>

  {% else %}
  <table class="table table-dark table-striped table-hover">
    <thead>
      <tr>
        <th style="text-align:center" scope="col">Title</th>
        <th style="text-align:center" scope="col">Description</th>
        <th style="text-align:center" scope="col">Min Salary</th>
        <th style="text-align:center" scope="col">Max Salary</th>
        <th style="text-align:center" scope="col">Location</th>
        <th style="text-align:center" scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for job in total_jobs.items %}
      {% if job.visibility == '1' %}
      <tr>
        <td style="text-align:center">{{ job.title }}</td>
        <td style="text-align:center">{{ job.descr }}</td>
        <td style="text-align:center">{{ job.salary_min }}</td>
        <td style="text-align:center">{{ job.salary_max }}</td>
        <td style="text-align:center">{{ job.location }}</td>
        {% if job.jobid in job_id_list %}
        <td style="text-align:center">{{ job_id_list[job.jobid] }}</td>
        {% else %}
        <td>
          <form method="POST" align="center">
            <input style="text-align:center" type="hidden" name="apply_job" value="{{job.jobid}}">
            <input style="text-align:center" type="submit"
              onclick="return confirm('Are you sure you want to apply for this job?')" value="Apply">
          </form>
        </td>
        {% endif %}
        {% endif %}

      </tr>
      {% endfor %}
    </tbody>
  </table>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for page_num in total_jobs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if total_jobs.page == page_num %}
      <li class="page-item disabled">
        <a class="page-link" href="{{ url_for('users.applicant_view', page=page_num) }}">{{ page_num }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link"
          href="{{ url_for('users.applicant_view', page=page_num) }}">{{ page_num }}</a></li>
      {% endif %}
      {% endfor %}
  </nav>
  {% endif %}
</div>

{% endblock %}

DB-Application directory/project/templates/applicant_attachments.html
{% extends "base.html" %}
{% block content %}

{% if warning %}
<div class="alert alert-warning" role="alert" align="center">
  {{warning}}
</div>
{% endif %}



{% if user_name %}
<h1>Welcome {{ user_name }}!!!</h1>
{% endif %}


<div class="jumbotron">
  <h2 ALIGN="center">PLEASE UPLOAD YOUR ADDITIONAL ATTACHMENTS FOR
    APPLICATION TRACKING SYSTEM
  </h2>
  <br>
  <br>
  <form method="POST" enctype="multipart/form-data">

    <div class="form-group">
      <label class="control-label">Cover Letter</label>
      <div class="custom-file">
        <input type="file" class="custom-file-input" name="cover_letter" aria-describedby="inputGroupFileAddon01">
        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
      </div>
    </div>

    <br>
    <script>
      // Add the following code if you want the name of the file appear on select
      $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
      });
    </script>

      <div class="form-group">
      <label class="control-label">Letter of Recommendation</label>
      <div class="custom-file">
        <input type="file" class="custom-file-input" name="lor" aria-describedby="inputGroupFileAddon01">
        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
      </div>
    </div>

    <br>
    <script>
      // Add the following code if you want the name of the file appear on select
      $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
      });
    </script>

      <div class="form-group">
      <label class="control-label">Transcripts</label>
      <div class="custom-file">
        <input type="file" class="custom-file-input" name="transcripts" aria-describedby="inputGroupFileAddon01">
        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
      </div>
    </div>

    <br>
    <script>
      // Add the following code if you want the name of the file appear on select
      $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
      });
    </script>


    <br>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

DB-Application directory/project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Farhaan</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</head>

<body>
  <ul class="nav">

    {% if current_user.is_authenticated %}

    <li class="nav-link">
      <a href="{{ url_for('users.logout') }}">Log Out</a>
    </li>

    {% if is_applicant %}
    <li class="nav-link">
      <a href="{{ url_for('users.applicant_attachments') }}">Attachments</a>
    </li>
    {% endif %}

    {% else %}


    <li class="nav-link">
      <a href="{{ url_for('core.index') }}">Home</a>
    </li>
    <li class="nav-link">
      <a href="{{ url_for('users.login') }}">Login</a>
    </li>
    <li class="nav-link">
      <a href="{{ url_for('admin.login') }}">Admin</a>
    </li>
    <li class="nav-link">
      <a href="{{ url_for('staff.login') }}">Staff Accounts</a>
    </li>
    <li class="nav-link">
      <a href="{{ url_for('users.register') }}">Register</a>
    </li>

    {% endif %}

  </ul>


  <div class="container">
    <div class="jumbotron">
      <h1 align="center">APPLICATION TRACKING SYSTEM</h1>
    </div>
    {% block content %}

    {% endblock %}
  </div>
</body>

</html>

DB-Application directory/project/templates/hr_recruiter_account_create.html
{% extends "base.html" %}
{% block content %}

{% if warning %}
<div class="alert alert-warning" role="alert">
  {{warning}}
</div>
{% endif %}


{% if success %}
<div class="alert alert-success" role="alert">
  {{success}}
</div>
{% endif %}


<div class="jumbotron">
  <h2 ALIGN="center">PLEASE REGISTER YOUR STAFF ACCOUNTS FOR
    APPLICATION TRACKING SYSTEM
  </h2>
  <br>
  <br>
  {% if department_list == [] %}
    <h3>PLEASE FIRST ADD DEPARTMENT FOR POSTING JOBS</h3>
    {% else %}
  <form method="POST">

    <div class="form-group">
      <label for="exampleInputEmail1">Username</label>
      <input type="text" class="form-control" name="username" placeholder="Enter your Username">
      <small id="emailHelp" class="form-text text-muted"></small>
    </div>

    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter your Email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" name="password" placeholder="Password">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">Confirm Password</label>
      <input type="password" class="form-control" name="repeat_password" placeholder="Repeat Password">
    </div>

  <fieldset class="form-group">
      <div class="row">
        <legend class="col-form-label col-sm-2 pt-0">Type</legend>
        <div class="col-sm-10">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="Hiring Manager">
            <label class="form-check-label" for="gridRadios1">
              Hiring Manager
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="Recruiter">
            <label class="form-check-label" for="gridRadios2">
              Recruiter
            </label>
          </div>
        </div>
      </div>
    </fieldset>

    <div class="form-group">
        <label for="exampleInputEmail1">Department</label>
        <div class="dropdown">
            <select class="form-control" id="rating" name="department">
                {% for i in department_list %}
                <option value={{i}}>{{i}}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  {% endif %}
</div>
{% endblock %}

DB-Application directory/project/templates/index.html
{% extends "base.html" %}
{% block content %}
{% if current_user.is_authenticated %}
<div class="jumbotron">
    <h1>APPLICATION TRACKING SYSTEM</h1>
    <p>Welcome to your new JOB PORTAL.
    </p>
  </div>

{% endif %}





  {% endblock %}

DB-Application directory/project/templates/login.html
{% extends "base.html" %}
{% block content %}

{% if warning %}
<div class="alert alert-warning" role="alert">
  {{warning}}
</div>
{% endif %}

{% if success %}
<div class="alert alert-success" role="alert">
  {{success}}
</div>
{% endif %}

<div class="jumbotron">
    <h2 align="center">PLEASE LOGIN FOR 
        APPLICATION TRACKING SYSTEM
        </h2><br><br>
  <form method="POST">

    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter your email">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" name="password" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

DB-Application directory/project/templates/register.html
{% extends "base.html" %}
{% block content %}

{% if warning %}
<div class="alert alert-warning" role="alert" align="center">
  {{warning}}
</div>
{% endif %}
  

<div class="jumbotron">
  <h2 ALIGN="center">PLEASE REGISTER FOR
    APPLICATION TRACKING SYSTEM
  </h2>
  <br>
  <br>
  <form method="POST" enctype="multipart/form-data">

    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter your Email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" name="password" placeholder="Password">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">Confirm Password</label>
      <input type="password" class="form-control" name="repeat_password" placeholder="Repeat Password">
    </div>

    <div class="form-group">
      <label for="exampleInputEmail1">Name</label>
      <input type="text" class="form-control" name="name" placeholder="Enter your Name">
      <small id="emailHelp" class="form-text text-muted"></small>
    </div>

    <fieldset class="form-group">
      <div class="row">
        <legend class="col-form-label col-sm-2 pt-0">Gender</legend>
        <div class="col-sm-10">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="male">
            <label class="form-check-label" for="gridRadios1">
              Male
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="female">
            <label class="form-check-label" for="gridRadios2">
              Female
            </label>
          </div>
        </div>
      </div>
    </fieldset>

    <!--  jQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />

    <!-- Form code begins -->
    <div class="form-group">
      <!-- Date input -->
      <label class="control-label" for="date">Date of Birth</label>
      <input class="form-control" id="date" name="date_of_birth" placeholder="MM/DD/YYY" type="text" />
    </div>
    <!-- Form code ends -->

    <script>
      $(document).ready(function () {
        var date_input = $('input[name="date_of_birth"]'); //our date input has the name "date"
        var container = $('.bootstrap-iso form').length > 0 ? $('.bootstrap-iso form').parent() : "body";
        var options = {
          format: 'mm/dd/yyyy',
          container: container,
          todayHighlight: true,
          autoclose: true,
        };
        date_input.datepicker(options);
      })
    </script>


    <div class="form-group">
      <label class="control-label">Resume</label>
      <div class="custom-file">
        <input type="file" class="custom-file-input" name="resume" aria-describedby="inputGroupFileAddon01">
        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
      </div>
    </div>

    <br>
    <script>
      // Add the following code if you want the name of the file appear on select
      $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
      });
    </script>




    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}